# 交易所配置
exchange:
  - name: binance       # 交易所名称
    testnet: false      # 是否使用测试网
    api_key: 
    secret_key: 


logging:
  level: INFO            # 日志级别
  log_dir: logs          # 日志目录
  max_file_size: 10MB    # 单文件最大尺寸
  retention_days: 7      # 保留天数

defaults:
  symbol: BTCUSDT        # 默认交易对
  timeframe: 1h          # 默认时间周期

ui:
  theme: dark            # 界面主题
